#version: '2'
#services:
#  zookeeper:
#    container_name: local-zookeeper
#    image: ubuntu/zookeeper:edge
#    ports:
#      - "2181:2181"
#  kafka:
#    container_name: local-kafka
#    image: ubuntu/kafka:3.1-22.04_beta
##    depends_on:
##      - zookeeper
#    ports:
#      - "9092:9092"
#      - "2181:2181"
#    environment:
#      TZ: UTC
#      ZOOKEEPER_HOST: host.docker.internal # 주키퍼 호스트
#      ZOOKEEPER_PORT: 2181
##      - KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1

# docker run -d --name local-zookeeper -e TZ=UTC -p 2181:2181 ubuntu/zookeeper:3.1-22.04_beta
# docker run -d --name local-kafka -e TZ=UTC -p 9092:9092 -e 2181:2181 -e ZOOKEEPER_HOST=host.docker.internal -e ZOOKEEPER_PORT=2181 ubuntu/kafka:3.1-22.04_beta

version: "3.8"

networks:
  kafka-net:
    driver: bridge

services:
  zookeeper:
    image: bitnami/zookeeper:3.7
    networks:
      - kafka-net
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:3
    networks:
      - kafka-net
    ports:
      - '9093:9093'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
